### ISSUE TITLE
Support overhang angle setting not honored

### ISSUE THREAD

**Issue by wjk** [ThomasRahm/CuraEngine#1] opened 2021-10-01 19:05 UTC
### Describe the bug

Consider the below image. This object was sliced at a setting of 50° maximum unsupported overhang; I have also tried it at 45°. However, either way, the amount of support generated only goes down to the 75° mark. This will cause my print to fail were I to print it as-is. (Upstream Cura’s tree supports wouldn’t work either.) I have fiddled with the slicing settings extensively; none of the changes I tried caused Cura to produce a different support structure.

<img width="1744" alt="Cura Screenshot" src="https://user-images.githubusercontent.com/1915951/135673311-69c81f7c-99b6-4b4b-9c3c-c81ea59b5bc1.png">

### Revision number displayed in the error message
N/A

### To Reproduce
1. Load the following object file: https://www.thingiverse.com/thing:1564848
2. Set the tree support settings to match the above image.
3. Press slice.

### The name of your CPU
“Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz.” Note that I am running Cura inside a VMware Fusion virtual machine running on a MacBook.

### Note
The above linked object is licensed under the Creative Commons Attribution license. There are no legal issues caused my sharing it with you directly, as long as I give the link to the original Thingiverse page. If the above instructions don’t reproduce the problem, I can share my full Cura output file. Thanks!

**Comment by wjk** [comment] 2021-10-07 16:44
My question here has since been answered in https://github.com/Ultimaker/Cura/issues/10523. I will have to find another model file, because the one I am testing with is not compatible with any tree supports (yours or upstream’s). Thanks!

**Comment by ThomasRahm** [comment] 2021-11-14 21:58
Just saw this now, GitHub didn't send me an email, sorry.
I agree that the behavior is not what it should be when selecting *Support Distance Priority: Z overrides X/Y* and setting a small *Minimum Support X/Y Distance*.
A non optimal result (but most likely better than nothing) can be achieved by selecting either:  

1. *Support Distance priority: X/Y overrides Z*
![Screenshot Angle Support2](https://user-images.githubusercontent.com/67757218/141698477-44cfe763-2ed9-44ad-ab7f-a70edef65704.PNG)

2. *Support Distance Priority: Z overrides X/Y* AND setting the *Minimum Support X/Y Distance* to something very small (e.g. 0) AND setting the *Support Horizontal Expansion* to about *Line Width*+*Minimum Support X/Y Distance*+*0.1*.
![Screenshot Angle Support](https://user-images.githubusercontent.com/67757218/141698485-c050c771-ba6b-47b2-aaa3-9af66c86762f.PNG)

In both solutions the actual distance between Support and Overhang can be larger than the *Support Top Distance*.

I will reopen this as for now as *Support Distance Priority: Z overrides X/Y* should also be able to generate support at such overhangs when the *Minimum Support X/Y Distance* is small.

**Comment by ThomasRahm** [comment] 2021-12-06 13:28
I released a new version where that bug should be fixed.
Can you confirm that the issue is now fixed for you ?

Please note that no support can generate if the overhang area on each layer is everywhere closer to the model than minimum x/y distance. In other words, minimum x/y distance "overwrites" support overhang angle.

**Closed as completed** 2022-01-03 15:28 UTC
Labels: bug

**Comment by wjk** [comment] 2022-01-03 21:00
@ThomasRahm Actually, the bug with the supports not touching was an issue in upstream Cura, not your algorithm. I filed https://github.com/Ultimaker/Cura/issues/10523 and it has since been fixed. The fix will be released in Cura 4.13; I have built Cura from source so I can use the new functionality now, and it works great.

**Comment by ThomasRahm** [comment] 2022-01-04 12:58
The fact that the bug also existed upstream was pure coincidence, as I completely rewrote the tree support there is nothing (except few lines from the support floor generation) of the upstream code left in my implementation. I guess this issue was just an easy to miss edge-case ^^
