### ISSUE TITLE
Floating support generated when support trunks overlap

### ISSUE THREAD

**Issue by vh-xvg** [ThomasRahm/CuraEngine#9] opened 2023-01-02 22:53 UTC
**Application Version**
<pre> UltiMaker-Cura-5.3.0-alpha+xmas-linux-modern.AppImage </pre>

**Platform**
<pre> Fedora 37, x86_64 </pre>

**Steps to Reproduce**
<pre> Open the attached project. Slice. Examine the support (outside the model) at around layer 410 </pre>

**Actual Results**
<p> Tree support trunk diameter was set to 50 for this case. The slicer created multiple trunks that overlap, and if you look around layer 410ish bits of floating support are created in mid air as the trunks start to taper. This obviously won't print properly </p>

**Expected results**
<p> I would expect the slicer to either (i) generate trunks that don't overlap, avoiding the problem, or (ii) include sufficient internal structure from the bed up to avoid floating support like this, or as a last resort (iii) disallow a configuration setting (in this case trunk diameter) that resulted in this sort of problem. </p>

**Additional Information**
<p> The following screenshot shows the problem area. I can obviously work around this problem by setting a smaller trunk size, but given the height of the overall support structure in this area the current 50mm setting is not unreasonable. Plus, Cura decided how many trunks to put down, and in this case decided they overlap. A bit of internal structure for the large loop of 9 trunks would be better in fact, the reason I've been printing with a support wall line count of 2 for this model is because with a wall count of 1 (with legacy tree support) the large trunk circuit would sometimes split apart or adrift in parts after a few hundred layers.  </p>

[CFFFP_5.3_lhs_inlet7_repaired_pla_s50.3mf.zip](https://github.com/ThomasRahm/CuraEngine/files/10333649/CFFFP_5.3_lhs_inlet7_repaired_pla_s50.3mf.zip)
![ss1](https://user-images.githubusercontent.com/65583537/210282827-19ce9a3b-41a5-478d-9588-8119f7525679.png)

**Comment by vh-xvg** [comment] 2023-01-02 23:31
<p> This can happen on the same database with the tree trunk size set to a smaller value of 35mm. Here's a screenshot showing a piece of mid-air support starting to grow by layer 394. </p>

![ss2](https://user-images.githubusercontent.com/65583537/210284829-e1e80e79-3595-4e32-b7a2-709a1fe71c35.png)

**Comment by DerGenaue** [comment] 2023-01-02 23:35
Duplicate of https://github.com/Ultimaker/Cura/issues/14166

Please also try disabling `Limit Branch Reach` or increasing `Tree Support Optimal Branch Range` to allow more Tree trunks to merge properly

**Comment by ThomasRahm** [comment] 2023-01-03 14:35
Illustration using paint:
Imagine you have three branches like this: 
![image](https://user-images.githubusercontent.com/67757218/210327025-bd7e4f5b-7672-4a74-863f-b77d14d74bba.png)
Now if these area are unioned (e.g. Lines that separate one support area from another be removed):
![image](https://user-images.githubusercontent.com/67757218/210327045-95ea3e98-3317-4455-855a-408857a81254.png)
You will suddenly have floating stuff in the middle of a combination of branches.
Not unioning the support areas, could cause overlapping lines, that cause even larger issues.
IMO, this is more of a theoretical issue, as the filament extruded mid-air will wipe of to the outer wall of the branch, effectively acting as small amount of spaghetti infill. It is not pretty, but i do not expect it to cause major problems

There seems to be an easy way to get rid of the worst offender of this issue (by removing all holes in support areas), but it causes support having sometimes ungodly amounts of overhang (which would not be this much of an issue if people were using 5-10% of support infill). 
Example:
![image](https://user-images.githubusercontent.com/67757218/210337298-19ff26c8-c1f0-4f9c-975d-a7708fced5b6.png)
In your opinion, do you think this would be an improvement ?

**Comment by vh-xvg** [comment] 2023-01-04 06:41
It's hard to decide whether that is an improvement based on what happens at the _beginning/bottom layer_ of the anomaly. It's what happens through the layers moving up that counts. The way I'd think about comparing the two (or more) cases would be to consider:

- Which case leads to stronger or more reliable support _at the support roof_, and
- Secondarily, which case leads to less "wasted" filament, and
- A distant third, which case might ultimately allow a (future) heuristic that could optimize away the wasted filament

I'm about to print this using 30mm support trunks, assuming that works I don't mind trying some of the anomalous cases to evaluate what the real world implications are. I don't mind trying experimental code if that helps (I'm a retired developer). It's a large model and a pretty good test case, I think. Three days per print though, so results won't come quickly.

**Comment by Optimaximal** [comment] 2023-02-01 20:14
@ThomasRahm do you want us to post new examples of this to this issue or create a new one? I've found a slightly different cause that's giving the same results?

**Comment by ThomasRahm** [comment] 2023-02-02 23:05
Only if they occur with CuraEngine.exe replaced with the one that contains the fixes for this, as i am only looking for bugs i have not yet fixed ;)
https://github.com/ThomasRahm/CuraEngine/releases/tag/5.3.0-alpha%2Bxmas%2Bfixes

**Closed as completed** 2023-05-23 21:23 UTC
